name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'PyPi Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Twine
        run: |
          pip install build twine

      - name: Build and Distribute
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build --sdist
          twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
